Execution result for concurrently

diff --git a/lib/concurrently b/lib/concurrently
--- a/lib/concurrently
+++ b/lib/concurrently
@@ -9,7 +9,7 @@ function concurrently() {
   lineWidth=$(($(echo ${JOB_NAME} | wc -c) + 25))
 
   progress=$(mktemp -d)
-  mkdir ${progress}/{active,completed}
+  mkdir ${progress}/{active,completed,failed}
 
   (
     progressIndicator=...
@@ -38,7 +38,9 @@ function concurrently() {
       (
         processId=$(uuidgen)
         touch ${progress}/active/${processId}
-        eval ${nextJob}
+        eval ${nextJob} || {
+          echo "${nextJob}" > ${progress}/failed/${processId};
+        }
         mv ${progress}/{active,completed}/${processId}
       ) &
   done
@@ -47,5 +49,14 @@ function concurrently() {
 
   wait
 
+  printf "%${lineWidth}s\r" ' '
+  if [[ $(ls -1 ${progress}/failed | wc -l) > 0 ]]; then
+    echo "${error}Failed to execute jobs:"
+    cat ${progress}/failed/* | sed 's/^/'"${listItem}"' /g'
+    rm -rf ${progress}
+    return 1
+  fi
+
   rm -rf ${progress}
+  return 0
 }
